// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShadowOfGoldBot.Data;

#nullable disable

namespace ShadowOfGoldBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001154827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ShadowOfGoldBot.Models.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlagToSet")
                        .HasColumnType("TEXT");

                    b.Property<int>("KarmaGreedChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextSceneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReputationGangChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReputationSheriffChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReputationTownChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredFlag")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredItem")
                        .HasColumnType("TEXT");

                    b.Property<int>("SceneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrustMayChange")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.Ending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Endings");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentSceneId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGameFinished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSceneId");

                    b.HasIndex("EndingId");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.PlayerFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SetAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerFlags");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.PlayerState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAmmo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasGold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRifle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KarmaGreed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReputationGang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReputationSheriff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReputationTown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrustMay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerStates");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.Choice", b =>
                {
                    b.HasOne("ShadowOfGoldBot.Models.Scene", "Scene")
                        .WithMany("Choices")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.Player", b =>
                {
                    b.HasOne("ShadowOfGoldBot.Models.Scene", "CurrentScene")
                        .WithMany()
                        .HasForeignKey("CurrentSceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShadowOfGoldBot.Models.Ending", "Ending")
                        .WithMany()
                        .HasForeignKey("EndingId");

                    b.Navigation("CurrentScene");

                    b.Navigation("Ending");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.PlayerFlag", b =>
                {
                    b.HasOne("ShadowOfGoldBot.Models.Player", "Player")
                        .WithMany("Flags")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.PlayerState", b =>
                {
                    b.HasOne("ShadowOfGoldBot.Models.Player", "Player")
                        .WithOne("State")
                        .HasForeignKey("ShadowOfGoldBot.Models.PlayerState", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.Player", b =>
                {
                    b.Navigation("Flags");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ShadowOfGoldBot.Models.Scene", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
